export const FALLBACK_MOVIES = [
  {
    id: 550,
    title: 'Fight Club',
    media_type: 'movie',
    release_date: '1999-10-15',
    vote_average: 8.4,
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    overview: 'A restless office worker and a soap maker build an underground movement that spirals into something much larger.',
  },
  {
    id: 603,
    title: 'The Matrix',
    media_type: 'movie',
    release_date: '1999-03-31',
    vote_average: 8.2,
    poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop_path: '/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    overview: 'A hacker discovers reality is a simulation and joins a rebellion against the machines controlling it.',
  },
  {
    id: 27205,
    title: 'Inception',
    media_type: 'movie',
    release_date: '2010-07-16',
    vote_average: 8.4,
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    overview: 'A thief who steals secrets through dream-sharing gets a chance at redemption with one impossible job.',
  },
  {
    id: 157336,
    title: 'Interstellar',
    media_type: 'movie',
    release_date: '2014-11-07',
    vote_average: 8.5,
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    overview: 'Explorers travel through a wormhole to find humanity a new home as Earth runs out of time.',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    media_type: 'movie',
    release_date: '2008-07-18',
    vote_average: 8.5,
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
    overview: 'Batman faces a criminal mastermind whose chaos pushes Gotham and its heroes to the edge.',
  },
  {
    id: 496243,
    title: 'Parasite',
    media_type: 'movie',
    release_date: '2019-05-30',
    vote_average: 8.5,
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: '/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg',
    overview: 'A struggling family infiltrates a wealthy household in a darkly funny thriller about class and survival.',
  },
];

export const FALLBACK_TV = [
  {
    id: 1396,
    name: 'Breaking Bad',
    media_type: 'tv',
    first_air_date: '2008-01-20',
    vote_average: 8.9,
    poster_path: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop_path: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    overview: 'A chemistry teacher turns to the drug trade, transforming himself and everyone around him.',
  },
  {
    id: 66732,
    name: 'Stranger Things',
    media_type: 'tv',
    first_air_date: '2016-07-15',
    vote_average: 8.6,
    poster_path: '/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    overview: 'A small town faces secret experiments, supernatural threats, and a group of kids at the center of it all.',
  },
  {
    id: 94605,
    name: 'Arcane',
    media_type: 'tv',
    first_air_date: '2021-11-06',
    vote_average: 8.7,
    poster_path: '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    backdrop_path: '/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    overview: 'Two sisters are caught on opposite sides of a conflict between rival cities and unstable magic.',
  },
  {
    id: 1399,
    name: 'Game of Thrones',
    media_type: 'tv',
    first_air_date: '2011-04-17',
    vote_average: 8.4,
    poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    overview: 'Noble families fight for power while an ancient threat gathers beyond the Wall.',
  },
  {
    id: 60574,
    name: 'Peaky Blinders',
    media_type: 'tv',
    first_air_date: '2013-09-12',
    vote_average: 8.5,
    poster_path: '/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
    backdrop_path: '/bGksau9GGu0uJ8DJQ8DYc9JW5LM.jpg',
    overview: 'A Birmingham crime family expands its power in the aftermath of World War I.',
  },
];

export const FALLBACK_ANIME = [
  {
    id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    media_type: 'anime',
    release_date: '2009-04-05',
    vote_average: 9.1,
    overview: 'Two brothers search for the Philosopher Stone after a forbidden ritual changes their lives.',
  },
  {
    id: 16498,
    title: 'Attack on Titan',
    media_type: 'anime',
    release_date: '2013-04-07',
    vote_average: 8.6,
    overview: 'Humanity fights for survival behind walls as the truth about the Titans begins to unravel.',
  },
  {
    id: 21,
    title: 'One Piece',
    media_type: 'anime',
    release_date: '1999-10-20',
    vote_average: 8.7,
    overview: 'A pirate crew searches for the world greatest treasure across a massive, dangerous sea.',
  },
  {
    id: 38000,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    media_type: 'anime',
    release_date: '2019-04-06',
    vote_average: 8.5,
    overview: 'A young swordsman joins the Demon Slayer Corps after his family is attacked.',
  },
];

export const FALLBACK_ANIMATION = [
  {
    id: 862,
    title: 'Toy Story',
    media_type: 'movie',
    release_date: '1995-11-22',
    vote_average: 8.0,
    poster_path: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
    backdrop_path: '/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg',
    overview: 'A cowboy doll feels threatened when a flashy space ranger becomes the new favorite toy.',
  },
  {
    id: 808,
    title: 'Shrek',
    media_type: 'movie',
    release_date: '2001-05-18',
    vote_average: 7.7,
    poster_path: '/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg',
    backdrop_path: '/sRvXNDItGlWCqtO3j6wks52FmbD.jpg',
    overview: 'An ogre, a talkative donkey, and a princess turn a fairy-tale rescue upside down.',
  },
  {
    id: 129,
    title: 'Spirited Away',
    media_type: 'movie',
    release_date: '2001-07-20',
    vote_average: 8.5,
    poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
    overview: 'A young girl enters a spirit world and must find courage to save her parents.',
  },
  {
    id: 324857,
    title: 'Spider-Man: Into the Spider-Verse',
    media_type: 'movie',
    release_date: '2018-12-14',
    vote_average: 8.4,
    poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    backdrop_path: '/uUiId6cG32JSRI6RyBQSvQtLjz2.jpg',
    overview: 'Miles Morales discovers a multiverse of Spider-heroes and learns what it means to wear the mask.',
  },
  {
    id: 10191,
    title: 'How to Train Your Dragon',
    media_type: 'movie',
    release_date: '2010-03-26',
    vote_average: 7.8,
    poster_path: '/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg',
    backdrop_path: '/aH9KWmXFMamXkHMgL6Yx2xXe3dP.jpg',
    overview: 'A young Viking befriends a dragon and changes the future of his village.',
  },
  {
    id: 354912,
    title: 'Coco',
    media_type: 'movie',
    release_date: '2017-11-22',
    vote_average: 8.2,
    poster_path: '/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
    backdrop_path: '/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
    overview: 'A music-loving boy journeys through the Land of the Dead to uncover his family story.',
  },
];

export const FALLBACK_TRENDING = [...FALLBACK_MOVIES, ...FALLBACK_TV, ...FALLBACK_ANIME, ...FALLBACK_ANIMATION];
